# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

# Before run pipeline please check the variables
# *** Library variables ***
# azureSubscription (only for deploy)

# *** Pipeline variables ***
# MajorVer
# MinorVer
# appServiceName (only for deploy)

# Changing the name the variable $(Build.BuildNumber) will change as well
name: $(MajorVer).$(MinorVer)$(Rev:.r)

# manual trigger
trigger:
  - none
#- main
#- develop

pool:
  name: Azure Pipelines
  vmImage: ubuntu-latest # Agent VM image name

resources:
  - repo: self

variables:
  - group: General
  - name: buildConfiguration
    value: "Release"
  - name: version
    value: "$(Build.BuildNumber)" # This variable is used to update the nuget version

# Single stage Build section
steps:
  - task: UseDotNet@2
    displayName: "Use NET9"
    inputs:
      version: "9.0.x"
      includePreviewVersions: true # Required for preview versions

  - task: NuGetAuthenticate@1
    displayName: "NuGet Authenticate"

  - task: DotNetCoreCLI@2
    displayName: "Build projects"
    inputs:
      command: "build"
      projects: "**/Host.csproj"
      arguments: "--configuration $(BuildConfiguration)" # Update this to match your need

  # Run the Test (after building)
  - task: DotNetCoreCLI@2
    displayName: "Run tests"
    inputs:
      command: "test"
      projects: "**/*Tests/*.csproj"
      arguments: '--configuration $(buildConfiguration) --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura'
      publishTestResults: true

  - task: PublishCodeCoverageResults@2
    displayName: "Publish code coverage report"
    inputs:
      codeCoverageTool: "Cobertura"
      summaryFileLocation: "$(Agent.TempDirectory)/**/coverage.cobertura.xml"

  # Publish the artifact to be ready for deploy
  - task: DotNetCoreCLI@2
    displayName: Publish
    inputs:
      command: "publish"
      publishWebProjects: true
      # arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
      # zipAfterPublish: True

  - task: CopyFiles@2
    displayName: "Copy Artifacts"
    inputs:
      targetFolder: "$(Build.ArtifactStagingDirectory)"

  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifacts"
    inputs:
      pathToPublish: "$(Build.ArtifactStagingDirectory)"
# Deploy the artifact on Azure
# Please move this step to the release pipeline
#- task: AzureRmWebAppDeployment@4
#  displayName: 'Deploy Azure App Service'
#  inputs:
#    connectionType: 'AzureRM'
#    azureSubscription: '$(AzureSubscription)'
#    appType: 'webAppLinux'
#    webAppName: '$(AppServiceName)'
#    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
#    runtimeStack: 'DOTNETCORE|9.0'
