# Build and push a Docker image to Docker hub
# The stage contains a couple of build and push
# One for the Version and one for Latest
# https://aka.ms/yaml
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

# NOTE: Each docker image shall tag with a unique number.
#        That number is the value coming from 'Build.BuildId' global variable

# Before run pipeline please check the variables
# *** Library variables ***
# DockerhubConnection:   The Docker Hub Service connection
# PatNugetsFeed:         The PAT to enable access to Private Nuget Feed

# *** Pipeline variables ***
# MajorVer:           The MajorVer Used for pipeline definition
# MinorVer:           The MinorVer Used for pipeline definition
# RepositoryName:     The name of the image to be created in Docker Hub including the repository
# HostFolder:         The folder name where the host with Dockerfile is placed it could be (WebApi|worker)

# Changing the name the variable $(Build.BuildNumber) will change as well
name: $(majorVer).$(minorVer)$(Rev:.r)

# manual trigger
trigger:
  - none

pool:
  name: Azure Pipelines
  vmImage: ubuntu-latest # Agent VM image name

resources:
  - repo: self

variables:
  # Here is how to read the Variables from Variable group
  - group: "General" # The variable group Name

stages:
  - stage: Build
    displayName: Docker Image
    condition: and(always(), contains(variables['Build.SourceBranch'], 'refs/heads/main'))
    jobs:
      - job: Build
        displayName: Build

        steps:
          - task: Docker@2
            displayName: "Build Image"
            inputs:
              command: build
              repository: $(RepositoryName)
              tags: "$(Build.BuildId),latest" # Use build number as tag
              dockerfile: "./src/$(HostFolder)/Dockerfile"
              arguments: --build-arg PAT_VALUE=$(PatNugetsFeed)
              buildContext: "./" # Uncomment if your Dockerfile is not in the root of the repo
              containerRegistry: "$(DockerhubConnection)" # The Docker Hub Service connection

          - task: Docker@2
            displayName: Push Image
            inputs:
              command: push
              repository: $(RepositoryName)
              tags: "$(Build.BuildId),latest"
              containerRegistry: "$(DockerhubConnection)" # The Docker Hub Service connection
              condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
